# Generated by Django 3.2.13 on 2022-05-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(blank=True, choices=[('P', 'Pending'), ('A', 'Accepted'), ('R', 'Rejected')], default='P', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
