# Generated by Django 3.2.13 on 2022-05-24 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220524_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='completed',
        ),
    ]
