# Generated by Django 3.2.13 on 2022-05-28 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_application_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='username',
        ),
    ]
