# Generated by Django 3.2.13 on 2022-05-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_application_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
